#!/usr/bin/env python3
"""Render the flash-gen-main-v1 SUMMARY.md and §2 tables.

Thin wrapper over `cir_workflow.gen_results` (shared with `cir_workflow
results`). Later `--batch` dirs override earlier cells for the same
(rep, task, arm).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "python"))

from cir_workflow import gen_results  # noqa: E402


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--batch", action="append", required=True)
    parser.add_argument("--out", default="experiments/flash-gen-main-v1")
    parser.add_argument("--tables", default="experiments/tables")
    args = parser.parse_args()
    batches = [Path(b) for b in args.batch]
    cells = gen_results.load_cells(batches)
    out = REPO / args.out
    out.mkdir(parents=True, exist_ok=True)
    (out / "SUMMARY.md").write_text(gen_results.render_md(cells, batches),
                                    encoding="utf-8")
    tables = REPO / args.tables
    tables.mkdir(parents=True, exist_ok=True)
    for name, body in gen_results.render_tex(cells).items():
        (tables / name).write_text(
            f"% {name} — generated by scripts/render_gen_main.py\n" + body,
            encoding="utf-8")
    print(f"rendered {len(cells)} cells -> {out/'SUMMARY.md'} + 3 tables")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
