#!/usr/bin/env python3
"""Render tables/gen_replay.tex from gen-code-replay-v2/RESULTS.json."""
import json
from pathlib import Path
REPO = Path(__file__).resolve().parents[1]
d = json.loads((REPO / "experiments/gen-code-replay-v2/RESULTS.json").read_text())
recs = d["records"]
fail = [r for r in recs if not r["before_accepted"]]
fb = [r for r in fail if not r["before_build"] and r["after_ok"]]
fc = [r for r in fail if r["before_build"] and r["after_ok"]]
still = [r for r in fail if not r["after_ok"]]
kinds = {}
for r in still:
    k = r["after"].get("kind")
    kinds[k] = kinds.get(k, 0) + 1
acc = [r for r in recs if r["before_accepted"]]
regr = [r for r in acc if not r["after_ok"]]
unmap = sum(1 for r in acc if r["after"].get("unmapped"))
body = ["% gen_replay.tex — generated by scripts/render_replay.py",
        "\\begin{tabular}{lr}", "\\toprule",
        "freeze-6 code failures & " + str(len(fail)) + " \\\\",
        "fixed by build harness & " + str(len(fb)) + " \\\\",
        "fixed by conform rule & " + str(len(fc)) + " \\\\",
        "still failing & " + str(len(still)) + " \\\\",
        "accepted-cell regressions & " + str(len(regr)) + " \\\\",
        "accepted cells with monitor unmapped & " + str(unmap) + "/" + str(len(acc)) + " \\\\",
        "\\bottomrule", "\\end{tabular}"]
(REPO / "experiments/tables/gen_replay.tex").write_text("\n".join(body) + "\n")
print("wrote gen_replay.tex")
