#!/usr/bin/env python3
"""Render flash-gen-main-v1 SUMMARY.md and the §2 LaTeX tables.

Merges one or more batch `SUMMARY.json` files; later batches override earlier
cells for the same (rep, task, arm). Cells are aggregated per arm, per tier and
overall with RC/RF, accept rate, defect rate and cost.
"""

from __future__ import annotations

import argparse
import json
import statistics
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ARMS = ("G0_direct", "G1_self_iter", "G2_tools_iter", "G3_concir")
TIERS = ("Simple", "Medium", "Complex")


def load_cells(batches: list[Path]) -> dict[tuple, dict]:
    cells: dict[tuple, dict] = {}
    for batch in batches:
        summary = json.loads((batch / "SUMMARY.json").read_text(encoding="utf-8"))
        for cell in summary["cells"]:
            if cell.get("status") == "not_run":
                continue
            cells[(cell["rep"], cell["task"], cell["arm"])] = cell
    return cells


def _mean(values):
    values = [v for v in values if v is not None]
    return round(statistics.mean(values), 3) if values else None


def _tokens(cell: dict) -> int:
    return (cell.get("prompt_tokens") or 0) + (cell.get("completion_tokens") or 0)


def _is_defect(cell: dict) -> bool:
    if not cell.get("accepted"):
        return False
    rec = cell.get("record") or {}
    if cell["arm"] == "G3_concir":
        conform = rec.get("conform") or {}
        return bool(rec.get("behavior_hang") or (conform.get("violation") or 0) > 0
                    or (rec.get("model") or {}).get("outcome") not in ("PASS", None))
    return bool(cell.get("hang") or cell.get("monitor_fail"))


def aggregate(cells: list[dict]) -> dict:
    accepted = [c for c in cells if c.get("accepted")]
    return {
        "n": len(cells),
        "accepted": len(accepted),
        "accept_rate": round(len(accepted) / len(cells), 3) if cells else None,
        "rc": _mean([c.get("rc") for c in cells]),
        "rf": _mean([c.get("rf") for c in cells]),
        "defect": sum(1 for c in cells if _is_defect(c)),
        "awp": sum(1 for c in cells if c.get("accepted_with_proof")),
        "tokens": sum(_tokens(c) for c in cells),
    }


def render_md(cells: dict, batches: list[Path] | None = None) -> str:
    all_cells = list(cells.values())
    lines = [
        "# flash-gen-main-v1 — generation (main)",
        "",
        "Requirements -> program, four arms, 24 tasks, K=4, 3 reps. Rust arms are",
        "scored by the bounded monitor (§1); G3 by the exhaustive model verdict +",
        "conform. The contract is hidden from every model prompt.",
    ]
    if batches:
        lines += ["", "Merged batches (later overrides earlier): "
                  + ", ".join(f"`{b.name}`" for b in batches) + "."]
    lines += [
        "",
        "## Per arm",
        "",
        "| arm | cells | accepted | accept rate | RC | RF | defect | accepted-with-proof | tokens |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for arm in ARMS:
        agg = aggregate([c for c in all_cells if c["arm"] == arm])
        lines.append(
            f"| {arm} | {agg['n']} | {agg['accepted']} | {agg['accept_rate']} | "
            f"{agg['rc']} | {agg['rf']} | {agg['defect']} | {agg['awp']} | {agg['tokens']} |")
    overall = aggregate(all_cells)
    lines.append(
        f"| **all** | {overall['n']} | {overall['accepted']} | {overall['accept_rate']} | "
        f"{overall['rc']} | {overall['rf']} | {overall['defect']} | {overall['awp']} | "
        f"{overall['tokens']} |")
    lines += ["", "## Per tier × arm (RF)", "",
              "| tier | " + " | ".join(ARMS) + " |",
              "| --- | " + " | ".join("---" for _ in ARMS) + " |"]
    for tier in TIERS:
        row = [tier]
        for arm in ARMS:
            agg = aggregate([c for c in all_cells if c["arm"] == arm and c.get("tier") == tier])
            row.append(str(agg["rf"]))
        lines.append("| " + " | ".join(row) + " |")
    lines += ["", "`defect` = accepted and (hang/behavior or monitor/conform violation).",
              "`accepted-with-proof` is G3-only (model PASS and conform PASS)."]
    return "\n".join(lines) + "\n"


def render_tex(cells: dict) -> dict[str, str]:
    all_cells = list(cells.values())
    main = ["% generated by scripts/render_gen_main.py", "\\begin{tabular}{lrrrrrr}",
            "\\toprule", "arm & cells & acc. & RF & defect & awp & tokens \\\\", "\\midrule"]
    for arm in ARMS:
        a = aggregate([c for c in all_cells if c["arm"] == arm])
        main.append(f"{arm.replace('_', chr(92)+'_')} & {a['n']} & {a['accept_rate']} & "
                    f"{a['rf']} & {a['defect']} & {a['awp']} & {a['tokens']} \\\\")
    a = aggregate(all_cells)
    main += ["\\midrule",
             f"all & {a['n']} & {a['accept_rate']} & {a['rf']} & {a['defect']} & "
             f"{a['awp']} & {a['tokens']} \\\\", "\\bottomrule", "\\end{tabular}"]
    arms = ["% generated by scripts/render_gen_main.py", "\\begin{tabular}{lrrr}", "\\toprule",
            "arm & acc. rate & RC & RF \\\\", "\\midrule"]
    for arm in ARMS:
        a = aggregate([c for c in all_cells if c["arm"] == arm])
        arms.append(f"{arm.replace('_', chr(92)+'_')} & {a['accept_rate']} & {a['rc']} & "
                    f"{a['rf']} \\\\")
    arms += ["\\bottomrule", "\\end{tabular}"]
    tiers = ["% generated by scripts/render_gen_main.py",
             "\\begin{tabular}{l" + "r" * len(ARMS) + "}", "\\toprule",
             "tier & " + " & ".join(a.replace("_", chr(92) + "_").replace("G", "G") for a in ARMS) + " \\\\",
             "\\midrule"]
    for tier in TIERS:
        row = [tier]
        for arm in ARMS:
            a = aggregate([c for c in all_cells if c["arm"] == arm and c.get("tier") == tier])
            row.append(str(a["rf"]))
        tiers.append(" & ".join(row) + " \\\\")
    tiers += ["\\bottomrule", "\\end{tabular}"]
    return {"gen_main.tex": "\n".join(main) + "\n",
            "gen_arms.tex": "\n".join(arms) + "\n",
            "gen_tiers.tex": "\n".join(tiers) + "\n"}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--batch", action="append", required=True)
    parser.add_argument("--out", default="experiments/flash-gen-main-v1")
    parser.add_argument("--tables", default="experiments/tables")
    args = parser.parse_args()
    batches = [Path(b) for b in args.batch]
    cells = load_cells(batches)
    out = REPO / args.out
    out.mkdir(parents=True, exist_ok=True)
    (out / "SUMMARY.md").write_text(render_md(cells, batches), encoding="utf-8")
    tables = REPO / args.tables
    tables.mkdir(parents=True, exist_ok=True)
    for name, text in render_tex(cells).items():
        (tables / name).write_text(text, encoding="utf-8")
    print(f"rendered {len(cells)} cells -> {out/'SUMMARY.md'} + 3 tables")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
