#!/usr/bin/env python3
"""Render tables/gen_replay.tex from gen-code-replay-v1/RESULTS.json."""
import json
from pathlib import Path
REPO = Path(__file__).resolve().parents[1]
d = json.loads((REPO / "experiments/gen-code-replay-v1/RESULTS.json").read_text())
recs = d["records"]
fail = [r for r in recs if not r["before_ok"]]
fixed = [r for r in fail if r["after"].get("conformant") == r["after"].get("traces") and r["after"].get("traces")]
kinds = {}
for r in fail:
    if r["after"].get("conformant") != r["after"].get("traces"):
        k = r["after"].get("kind")
        kinds[k] = kinds.get(k, 0) + 1
body = ["% gen_replay.tex — generated by scripts/render_replay.py",
        "\\begin{tabular}{lr}", "\\toprule",
        "freeze-5 code failures & " + str(len(fail)) + " \\\\",
        "harness gap (fixed by toolchain) & " + str(len(fixed)) + " \\\\",
        "still failing & " + str(len(fail) - len(fixed)) + " \\\\",
        "remaining kind: extra\\_op & " + str(kinds.get("extra_op", 0)) + " \\\\",
        "smoke conform (before $\\to$ after) & 15/45 $\\to$ " + str(d.get("smoke", {}).get("smoke_conform_ok")) + "/" + str(d.get("smoke", {}).get("smoke_total")) + " \\\\",
        "\\bottomrule", "\\end{tabular}"]
(REPO / "experiments/tables/gen_replay.tex").write_text("\n".join(body) + "\n")
print("wrote gen_replay.tex")
