#!/usr/bin/env python3
"""§3 frontier-model probe: G0/G2/G3 on all tasks, 1 rep, OpenCode Go.

Model preference: kimi-k3, else kimi-k2.7-code. Budget <= 150 requests; cells
that do not run are recorded `not_run` with a reason. Writes
`experiments/gen-model-probe-v1/{SUMMARY.json,SUMMARY.md}` and
`experiments/tables/gen_probe.tex`.
"""

from __future__ import annotations

import argparse
import json
import os
import statistics
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "python"))

from cir_workflow.env import load_dotenv  # noqa: E402
from cir_workflow.generation import (  # noqa: E402
    load_gen_tasks, run_g3, run_rust_generation, rust_arm_oracle,
)
from cir_workflow.live import LiveBudget  # noqa: E402
from cir_workflow.opencode_go import OpenCodeGoClient, list_models  # noqa: E402

ARMS = ("G0_direct", "G2_tools_iter", "G3_concir")
PREFERRED = ("kimi-k3", "kimi-k2.7-code")


def resolve_model(api_key: str) -> str:
    try:
        data = list_models(api_key)
        ids = [m.get("id", "") for m in data.get("data", [])]
    except Exception:  # noqa: BLE001
        ids = []
    for name in PREFERRED:
        if name in ids:
            return name
    for mid in ids:
        if "kimi" in mid:
            return mid
    return PREFERRED[-1]


def _mean(values):
    values = [v for v in values if v is not None]
    return round(statistics.mean(values), 3) if values else None


def _defect(cell: dict) -> bool:
    if not cell.get("accepted"):
        return False
    rec = cell.get("record") or {}
    if cell["arm"] == "G3_concir":
        conform = rec.get("conform") or {}
        return bool(rec.get("behavior_hang") or (conform.get("violation") or 0) > 0
                    or (rec.get("model") or {}).get("outcome") not in ("PASS", None))
    return bool(cell.get("hang") or cell.get("monitor_fail"))


def _tokens(cell: dict) -> int:
    return (cell.get("prompt_tokens") or 0) + (cell.get("completion_tokens") or 0)


def aggregate(cells: list[dict]) -> dict:
    ran = [c for c in cells if c.get("status") != "not_run"]
    accepted = [c for c in ran if c.get("accepted")]
    return {
        "n": len(ran), "not_run": len(cells) - len(ran),
        "accepted": len(accepted),
        "accept_rate": round(len(accepted) / len(ran), 3) if ran else None,
        "rc": _mean([c.get("rc") for c in ran]),
        "rf": _mean([c.get("rf") for c in ran]),
        "defect": sum(1 for c in ran if _defect(c)),
        "awp": sum(1 for c in ran if c.get("accepted_with_proof")),
        "tokens": sum(_tokens(c) for c in ran),
    }


def render(model: str, cells: list[dict], temperature) -> tuple[str, str]:
    lines = [
        "# gen-model-probe-v1 — generation with a frontier model",
        "",
        f"Model `{model}` (OpenCode Go, chat/completions), 1 rep, K=4, "
        f"temperature {temperature}. Arms G0/G2/G3 on all 24 tasks; same oracle "
        "as the main batch (bounded monitor for Rust, exhaustive model + conform "
        "for G3).",
        "",
        "| arm | cells | not_run | accepted | accept rate | RC | RF | defect | awp | tokens |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for arm in ARMS:
        a = aggregate([c for c in cells if c["arm"] == arm])
        lines.append(f"| {arm} | {a['n']} | {a['not_run']} | {a['accepted']} | "
                     f"{a['accept_rate']} | {a['rc']} | {a['rf']} | {a['defect']} | "
                     f"{a['awp']} | {a['tokens']} |")
    a = aggregate(cells)
    lines.append(f"| **all** | {a['n']} | {a['not_run']} | {a['accepted']} | "
                 f"{a['accept_rate']} | {a['rc']} | {a['rf']} | {a['defect']} | "
                 f"{a['awp']} | {a['tokens']} |")
    lines += ["", "Temperature is forced to 1 by the provider for models that "
              "reject 0; recorded per request in `llm/requests.jsonl`."]

    tex = ["% generated by scripts/run_gen_probe.py",
           "\\begin{tabular}{lrrrrrr}", "\\toprule",
           "arm & acc. & RC & RF & defect & awp & tokens \\\\", "\\midrule"]
    for arm in ARMS:
        a = aggregate([c for c in cells if c["arm"] == arm])
        tex.append(f"{arm.replace('_', chr(92)+'_')} & {a['accept_rate']} & {a['rc']} & "
                   f"{a['rf']} & {a['defect']} & {a['awp']} & {a['tokens']} \\\\")
    tex += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n", "\n".join(tex) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-requests", type=int, default=150)
    parser.add_argument("--k", type=int, default=4)
    parser.add_argument("--out", default="experiments/gen-model-probe-v1")
    parser.add_argument("--binary", default=os.environ.get(
        "CONCIR_BACKEND", "concir/target/release/concir-backend"))
    args = parser.parse_args()

    load_dotenv(REPO / ".env")
    api_key = os.environ.get("OPENCODE_API_KEY", "")
    if not api_key:
        print("OPENCODE_API_KEY missing", file=sys.stderr)
        return 2
    model = resolve_model(api_key)
    binary = Path(args.binary)
    tasks = load_gen_tasks(REPO)

    out = REPO / args.out
    batch = out / f"run-{time.strftime('%Y%m%dT%H%M%S')}"
    batch.mkdir(parents=True, exist_ok=True)
    budget = LiveBudget(batch / "budget.json", max_requests=args.max_requests,
                        max_seconds=6 * 3600)
    cells: list[dict] = []
    temperature = None
    stop = None
    for arm in ARMS:
        for task in tasks:
            reason = budget.exhausted()
            if reason:
                cells.append({"arm": arm, "task": task.id, "tier": task.tier,
                              "status": "not_run", "reason": reason})
                stop = reason
                continue
            cell_dir = batch / task.id.replace("/", "__") / arm
            cell_dir.mkdir(parents=True, exist_ok=True)
            started = time.monotonic()
            record: dict = {"arm": arm, "task": task.id}
            try:
                client = OpenCodeGoClient(
                    api_key=api_key, budget=budget, evidence_dir=batch / "llm",
                    model=model, timeout=120.0, max_tokens=4096)
                if arm == "G3_concir":
                    record = run_g3(client, binary, task, cell_dir, k=args.k)
                else:
                    run, record = run_rust_generation(client, arm, task, cell_dir,
                                                      k=args.k, miri_seeds=16)
                    artifact = run.final_artifact_path
                    if artifact:
                        oracle = rust_arm_oracle(Path(artifact), task,
                                                 cell_dir / "oracle", binary=binary)
                        record["oracle"] = oracle
                        record["coverage"] = oracle.get("coverage")
                        record["monitor_fail"] = oracle.get("monitor_fail")
                temperature = client.temperature
            except Exception as exc:  # noqa: BLE001
                record = {"arm": arm, "task": task.id, "status": "error",
                          "error": f"{type(exc).__name__}: {exc}"}
            pt = ct = 0
            for rnd in record.get("rounds", []):
                pt += int(rnd.get("prompt_tokens") or 0)
                ct += int(rnd.get("completion_tokens") or 0)
            cov = record.get("coverage") or {}
            cells.append({
                "arm": arm, "task": task.id, "tier": task.tier,
                "accepted": record.get("accepted"),
                "rounds": len(record.get("rounds", [])),
                "prompt_tokens": pt, "completion_tokens": ct,
                "rc": cov.get("rc"), "rf": cov.get("rf"),
                "hang": (record.get("oracle") or {}).get("hang"),
                "monitor_fail": record.get("monitor_fail"),
                "accepted_with_proof": record.get("accepted_with_proof"),
                "status": record.get("status"), "record": record,
                "verify_ms": int((time.monotonic() - started) * 1000),
            })
            (cell_dir / "CELL.json").write_text(
                json.dumps(record, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            (batch / "SUMMARY.json").write_text(
                json.dumps({"model": model, "cells": cells, "stop_reason": stop},
                           ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            print(f"{arm} {task.id} accepted={cells[-1]['accepted']} "
                  f"rf={cells[-1]['rf']} reqs={budget.requests_used}", flush=True)

    md, tex = render(model, cells, temperature)
    summary = {"model": model, "temperature": temperature, "cells": cells,
               "stop_reason": stop, "requests_used": budget.requests_used,
               "batch_dir": str(batch)}
    (batch / "SUMMARY.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (batch / "SUMMARY.md").write_text(md, encoding="utf-8")
    out.mkdir(parents=True, exist_ok=True)
    (out / "SUMMARY.md").write_text(md, encoding="utf-8")
    (REPO / "experiments/tables/gen_probe.tex").write_text(tex, encoding="utf-8")
    print(f"done: {budget.requests_used} requests, stop={stop}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
